spring:
  config:
    import: optional:file:.env[.properties]  # ✅ .env에서 값 불러오기
  application:
    name: app1

  datasource:
    url: jdbc:mysql://mysqltest-container:3306/cpgndb?characterEncoding=UTF-8
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8003
  servlet:
    session:
      cookie:
        same-site: Lax
        secure: false

file:
  upload-dir: /uploads

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
